### ISSUE TITLE
Trojan found by Windows AV, false positive?

### ISSUE THREAD

**Issue by RealJonto** [Sehyn/Wuwa_fpsunlocker#3]
![trojan-found](https://github.com/Sehyn/Wuwa_fpsunlocker/assets/170613291/59749d4e-eeb1-411a-b27d-ea01fc7171ed)
My windows is in Swedish, but it says that it is a critical threat. Is this a case of a false positive?

**Comment by Sehyn** [comment]
You can check the full code software at it is open source and see what it does on your PC, or compile it by yourself but this is a false positive
