### ISSUE TITLE
How to change the game path :) ?

### ISSUE THREAD

**Issue by ClemBlanc** [Sehyn/Wuwa_fpsunlocker#4]
If my game is in F:/Games/WutheringWaves
Is there a way to simply change the path, and where it is? (in which file)

First time using visual studio code + im a noob 😎 
Otherwise ill wait for your update

**Comment by Sehyn** [comment]
Yeah I can imagine that not everyone uses default path, I will make it so you can input the path yourself

**Comment by Sehyn** [comment]
> If my game is in F:/Games/WutheringWaves Is there a way to simply change the path, and where it is? (in which file)
> 
> First time using visual studio code + im a noob 😎 Otherwise ill wait for your update

https://github.com/Sehyn/Wuwa_fpsunlocker/releases/tag/V1.2

Here the fix, make sure to give the FULL path when the program asks you:

Example your file is in: `C:\Wuthering Waves\Wuthering Waves Game\Client\Saved\LocalStorage`

And the file name is: `LocalStorage.db`

Make sure to enter: `C:\Wuthering Waves\Wuthering Waves Game\Client\Saved\LocalStorage\LocalStorage.db`

**Comment by ClemBlanc** [comment]
Ok I tried for a bit but im so lost xD
Je viens de voir que tu es fr! Est-ce que ça te dis de voc discord pour m'expliquer comment faire? Je suis aussi monteur vidéo comme ça je pourrai faire un tuto pour la commu derrière.
mime101 sur discord

**Comment by Sehyn** [comment]
> Ok I tried for a bit but im so lost xD Je viens de voir que tu es fr! Est-ce que ça te dis de voc discord pour m'expliquer comment faire? Je suis aussi monteur vidéo comme ça je pourrai faire un tuto pour la commu derrière. mime101 sur discord

Je viens de t'envoyer une invite sous le nom d'Arthur (impots)

**Comment by Artur-Galis** [comment]
![image](https://github.com/Sehyn/Wuwa_fpsunlocker/assets/81031994/900a7972-55ee-4a69-9aff-6d61bf1a5beb)
How to fix this

**Comment by flawsv** [comment]
> ![image](https://private-user-images.githubusercontent.com/81031994/333215016-900a7972-55ee-4a69-9aff-6d61bf1a5beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzM5NzksIm5iZiI6MTcxNjQ3MzY3OSwicGF0aCI6Ii84MTAzMTk5NC8zMzMyMTUwMTYtOTAwYTc5NzItNTVlZS00YTY5LTlhZmYtNmQ2MWJmMWE1YmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0MTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzM2MyZjBmZDQ3MTMwOTc4ODAzZjE1NWM3NjM5NWQ2NWQyZGI1YzFjYTdjODJjZjVjMGIxZTBjOGIxNTdjNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1NqceIqZdYX9QC3ppFGUKpgSui7ZV-2sbd3kdtCJ-gs) How to fix this

Right click the fps unlocker and run it as administrator. Fixed that issue for me.

**Comment by Artur-Galis** [comment]
I tried it and it was still throwing the same error

**Comment by Sehyn** [comment]
> ![image](https://private-user-images.githubusercontent.com/81031994/333215016-900a7972-55ee-4a69-9aff-6d61bf1a5beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NzYwNzksIm5iZiI6MTcxNjQ3NTc3OSwicGF0aCI6Ii84MTAzMTk5NC8zMzMyMTUwMTYtOTAwYTc5NzItNTVlZS00YTY5LTlhZmYtNmQ2MWJmMWE1YmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE0NDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzZWNiNzQ2NzU3Nzk4OWEyYjBiNWMwNmZhMjZmODA2NmMyOTYzNTg4ZjFjMmNmNWVjYmRlZTFjYjcwZDg2MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FrHo5RanF1HqgPDHQaM1JF1m9SZ6QaHzLqHrf_lEu2A) How to fix this

Close your game its the first step!
