### ISSUE TITLE
Add an option to set an amount of FPS

### ISSUE THREAD

**Issue by metarima** [Sehyn/Wuwa_fpsunlocker#8]
For example, if i only want 165 fps i would be pretty cool if i could set just that amount instead of being uncapped fully!

**Comment by Khangry** [comment]
> For example, if i only want 165 fps i would be pretty cool if i could set just that amount instead of being uncapped fully!

I tried to set it to 200 fps but nothing different, just only 120fps. Need someone else confirm.

**Comment by 0x6DD8** [comment]
just tested, it's capped to 120fps

**Comment by Sehyn** [comment]
I can do that but won't be of any use because of the game engine limitation which is 120 FPS, but if it's needed I can do it yes

**Comment by sol029** [comment]
Would love a slider like the Genshin fps unlocker to 175 and beyond! Or at least a prompt to choose.
120 just doesn't feel smooth enough even though I'm constantly capped

**Comment by Sehyn** [comment]
> Would love a slider like the Genshin fps unlocker to 175 and beyond! Or at least a prompt to choose.
> 
> 120 just doesn't feel smooth enough even though I'm constantly capped

Noted update will be pushed today with a prompt to choose FPS amount and other tweaks

**Comment by Sehyn** [comment]
Your wishes have come true!

![image](https://github.com/Sehyn/Wuwa_fpsunlocker/assets/48888351/23f28f73-e2b9-4730-98c9-78ca8a88d044)


Download: https://github.com/Sehyn/Wuwa_fpsunlocker/releases/tag/V1.3

**Comment by sol029** [comment]
> Your wishes have come true!
> 
> ![image](https://private-user-images.githubusercontent.com/48888351/333792478-23f28f73-e2b9-4730-98c9-78ca8a88d044.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzQzODcsIm5iZiI6MTcxNjYzNDA4NywicGF0aCI6Ii80ODg4ODM1MS8zMzM3OTI0NzgtMjNmMjhmNzMtZTJiOS00NzMwLTk4YzktNzhjYThhODhkMDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEwNDgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzc3NWI2NGRiNjI3NTVjNWYyOWViNWYzNDBkZDY4NTY1ZTRiMzZhOGYxZmE4MTQ3YzYxNzRlYjc5YTk3ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8gMcKAaKggdl53epVkRNG8r5I0GNAFOmZ8qnHJ_2Ak)
> 
> Download: https://github.com/Sehyn/Wuwa_fpsunlocker/releases/tag/V1.3

KING.

**Comment by TwiceSNG** [comment]
Noticed that using default game location throws this error, but when I move WUWA to the placeholder location the tool works fine, and in-game if I change the fps cap, the tool effect gets removed.
![Screenshot_96](https://github.com/Sehyn/Wuwa_fpsunlocker/assets/170982274/6b86eac0-685b-4aa6-8877-49148d94fe2a)
